# Generated by Django 5.2.7 on 2025-11-30 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lala_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
