# Generated by Django 5.2.7 on 2025-11-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lala_app', '0002_alter_producto_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='clientes/'),
        ),
    ]
