# Generated by Django 5.2.7 on 2025-12-03 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lala_app', '0003_cliente_direccion_cliente_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='completada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('pendiente', '⏳ Pendiente'), ('completado', '✅ Completado')], default='pendiente', max_length=20),
        ),
    ]
